language: ruby
rvm:
  - 2.2.1
  - 2.1.5
  - 2.0.0
  - ruby-head
matrix:
  allow_failures:
    - rvm: ruby-head
script: bundle exec rake test
notifications:
  email:
    - dj2+goliath.build@everburning.com
